spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: yhlee0318**
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  profiles:
    active: local

jwt:
  token:
    secret-key: umceightfightingjwttokenauthentication
  expiration:
    access: 14400000


slack:
  webhook:
    url: <https://hooks.slack.com/services/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>
